version: "3.7"

services:
  # MongoDB
  teedata_bot_mongo:
    image: mongo
    container_name: teedata_bot_mongo
    volumes:
      - teedata_mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    restart: always

  # Discord bot
  teedata_bot:
    image: teedata
    container_name: teedata_bot
    build: .
    env_file: .env
    environment:
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@teedata_bot_mongo?authSource=admin
    depends_on:
      - teedata_bot_mongo
    restart: always

volumes:
  teedata_mongodb:
